### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by onedollar7** [CaptainDeathead/Eatventure-Bot#8]
Hello, I am trying to use the bot but after using python3 updater.py the script does not find the recuests module. I am stuck there

**Comment by CaptainDeathead** [comment]
So sorry,

I forgot to add it to the requirements file :(

Try running the command `pip install requests` to fix it.

Ill get on to fixing it right away.

Any problems just let me know.

Cheers.

**Comment by onedollar7** [comment]
Perfect, it was solved, now I am blocked with the phone's IP, I have tried several IPs, I have opened ports and the console always gives me an error...
 PHONE_IP_ADDRESS: str = CONFIG["xxx.xxx.x.xx"]
KeyError: 'xxx.xxx.x.xx'
even adding the port 

I am using everything as you explain

**Comment by CaptainDeathead** [comment]
You shouldn'd have to change `PHONE_IP_ADDRESS` in data. `PHONE_IP_ADDRESS: str = CONFIG["PHONE_IP_ADDRESS"]` is what it should be. it will automatically setup your ip address when you run the bot.

**Comment by CaptainDeathead** [comment]
EDIT: I just reallised it said to do that in the readme, and i have just changed it. I've done some updates so yeah, it does it automatically now. Itll ask you for your phones ip when you run it. Sorry.
