### ISSUE TITLE
Failed to connect to the phone, please try again with a new different IP address!

### ISSUE THREAD

**Issue by ksk233** [CaptainDeathead/Eatventure-Bot#9]
Hi, i did everything you instructed but when I am going to run it with python updater.py its says "Failed to connect to the phone, please try again with a new different IP address!" then asks for IP. tried with different ports but is always showing the same massage.
can you help, please?

![sefgsdfsdsfsd](https://github.com/user-attachments/assets/849c83c1-a65d-42a4-9c1a-91d9d51e9054)

**Comment by CaptainDeathead** [comment]
Do you have droidVNC running on android, if so it will yell you your phones IP address and port.

If you are on ios unfortunatly they do not support VNC to my knowledge :(

**Comment by ksk233** [comment]
Yes i got that IP and port after starting the droidVNC. could it be an issue with python soft? As I cannot run python3 updater.py, I need to use python updater.py.

**Comment by CaptainDeathead** [comment]
Is your phone on the same wifi as computer?

Also maybe try not putting to port number in, just the ip address.

**Comment by ksk233** [comment]
> Is your phone on the same wifi as computer?
> Yes

> Also maybe try not putting to port number in, just the ip address.
>tried both

**Comment by ksk233** [comment]
Update: after reinstalling Python and some changes, I was finally able to start the bot, but it seems very very slow, should I change anything? it is only going to upgrades option and only opening and upgrading the last foods.  like the way it clicks it would take a couple of hours or more to complete a station (I am at 60 City) which I could complete within 10-15 min max. Is there anything I can do about it. 

Thanks a lot for the work you put in on this, really appreciate the efforts.

**Comment by CaptainDeathead** [comment]
Cheers :)

The reason the bot isn't doing the top station is because it needs to be tinkered with because your on a different device.
The scrolling is a bit bugged because eatventure has custom scrolling functionality.

To get the bot working better on your device, open `data.py` in notepad and try lowering these values by just a smidge, to low and the Ai will click other random stuff.

```
# Confordence values
STATION_UPGRADES_CONFORDENCE: float = 0.8
CRATES_CONFORDENCE: float = 0.8
EXPLINATION_CONFORDENCE: float = 0.85
POPUP_CONFORDENCE: float = 0.8
RENOVATE_UPGRADE_CONFORDENCE: float = 0.8
```

To stop the autoscroll simply set `max_scrolls` to 0 in the menu.

**Comment by CaptainDeathead** [comment]
Sorry mate, didn't see your messages :(
Thanks a lot!
(Oops wrong issue)
